"""create initial schema

Revision ID: 20cfcd9a8300
Revises: 
Create Date: 2026-05-11 17:00:26.034811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '20cfcd9a8300'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('mime_type', sa.String(length=150), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('parsing_status', sa.String(length=50), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_knowledge_documents_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents'))
    )
    op.create_index(op.f('ix_knowledge_documents_company_id'), 'knowledge_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_document_type'), 'knowledge_documents', ['document_type'], unique=False)
    op.create_table('procurement_history_items',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('purchased_at', sa.Date(), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_procurement_history_items_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_history_items'))
    )
    op.create_index(op.f('ix_procurement_history_items_category'), 'procurement_history_items', ['category'], unique=False)
    op.create_index(op.f('ix_procurement_history_items_company_id'), 'procurement_history_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_procurement_history_items_sku'), 'procurement_history_items', ['sku'], unique=False)
    op.create_index(op.f('ix_procurement_history_items_supplier_name'), 'procurement_history_items', ['supplier_name'], unique=False)
    op.create_table('request_items',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('requested_quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('required_delivery_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_request_items_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_items'))
    )
    op.create_index(op.f('ix_request_items_category'), 'request_items', ['category'], unique=False)
    op.create_index(op.f('ix_request_items_company_id'), 'request_items', ['company_id'], unique=False)
    op.create_table('supplier_profiles',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('relationship_status', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_supplier_profiles_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_profiles'))
    )
    op.create_index(op.f('ix_supplier_profiles_company_id'), 'supplier_profiles', ['company_id'], unique=False)
    op.create_index(op.f('ix_supplier_profiles_name'), 'supplier_profiles', ['name'], unique=False)
    op.create_table('user_profiles',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_user_profiles_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles'))
    )
    op.create_index(op.f('ix_user_profiles_company_id'), 'user_profiles', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=False)
    op.create_table('negotiation_projects',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('request_item_id', sa.UUID(), nullable=True),
    sa.Column('supplier_profile_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('negotiation_type', sa.String(length=100), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('strategy_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('simulation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_negotiation_projects_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user_profiles.id'], name=op.f('fk_negotiation_projects_owner_id_user_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_item_id'], ['request_items.id'], name=op.f('fk_negotiation_projects_request_item_id_request_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_profile_id'], ['supplier_profiles.id'], name=op.f('fk_negotiation_projects_supplier_profile_id_supplier_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_negotiation_projects'))
    )
    op.create_index(op.f('ix_negotiation_projects_company_id'), 'negotiation_projects', ['company_id'], unique=False)
    op.create_index(op.f('ix_negotiation_projects_owner_id'), 'negotiation_projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_negotiation_projects_request_item_id'), 'negotiation_projects', ['request_item_id'], unique=False)
    op.create_index(op.f('ix_negotiation_projects_status'), 'negotiation_projects', ['status'], unique=False)
    op.create_index(op.f('ix_negotiation_projects_supplier_profile_id'), 'negotiation_projects', ['supplier_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_negotiation_projects_supplier_profile_id'), table_name='negotiation_projects')
    op.drop_index(op.f('ix_negotiation_projects_status'), table_name='negotiation_projects')
    op.drop_index(op.f('ix_negotiation_projects_request_item_id'), table_name='negotiation_projects')
    op.drop_index(op.f('ix_negotiation_projects_owner_id'), table_name='negotiation_projects')
    op.drop_index(op.f('ix_negotiation_projects_company_id'), table_name='negotiation_projects')
    op.drop_table('negotiation_projects')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_company_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_supplier_profiles_name'), table_name='supplier_profiles')
    op.drop_index(op.f('ix_supplier_profiles_company_id'), table_name='supplier_profiles')
    op.drop_table('supplier_profiles')
    op.drop_index(op.f('ix_request_items_company_id'), table_name='request_items')
    op.drop_index(op.f('ix_request_items_category'), table_name='request_items')
    op.drop_table('request_items')
    op.drop_index(op.f('ix_procurement_history_items_supplier_name'), table_name='procurement_history_items')
    op.drop_index(op.f('ix_procurement_history_items_sku'), table_name='procurement_history_items')
    op.drop_index(op.f('ix_procurement_history_items_company_id'), table_name='procurement_history_items')
    op.drop_index(op.f('ix_procurement_history_items_category'), table_name='procurement_history_items')
    op.drop_table('procurement_history_items')
    op.drop_index(op.f('ix_knowledge_documents_document_type'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_company_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
